### ISSUE TITLE
Can´t download SKSE 1.6.629.0

### ISSUE THREAD

**Issue by rperezandreiuk** [aljoxo/Arisen#8]
Unable do download SKSE 1.6.629.0 
Does anyone know what is happening? Should I do something or just wait?
Thanks in advance.

**Comment by aljoxo** [comment]
The list uses 1.5.97 version of SKSE

If your issue is due to Wabbajack failing to hash Skyrim.exe, that is because I haven't compiled the list since this last weeks update (September 20). You can try to rollback on steam if you'd like.

I would suggest that you check out the installation help section of the discord (discord.gg/WakingDreams)
